spring:
  thymeleaf:
    cache: true  # cache activé en production
  cloud:
    openfeign:
      client:
        config:
          default:
            loggerLevel: NONE  # aucun log des requêtes/réponses Feign en production

logging:
  level:
    com.tortiki.frontend: WARN
    feign: WARN